const initialValues = {
    name: 'Mandacaru',
    formats: [
        {
            name: 'A4 - Paisagem (21x29 cm)',
            id: 503,
            size: {
                width: 21,
                length: 29,
                // height: 2.5,
                height: 3,
                weight: 0.5,
            },
            types: [],
        },
        {
            name: 'A4 - Retrato (29x21 cm)',
            id: 504,
            size: {
                width: 21,
                length: 29,
                // height: 2.5,
                height: 3,
                weight: 0.5,
            },
            types: [],
        },
        {
            name: 'A5 - Paisagem (15x21 cm)',
            id: 505,
            size: {
                width: 15,
                length: 21,
                // height: 2.5,
                height: 3,
                weight: 0.5,
            },
            types: [],
        },
        {
            name: 'A5 - Retrato (21x15 cm)',
            id: 506,
            size: {
                width: 15,
                length: 21,
                // height: 2.5,
                height: 3,
                weight: 0.5,
            },
            types: [],
        },
        {
            name: 'A6 - Paisagem (10,5x15 cm)',
            id: 507,
            size: {
                width: 11,
                // width: 10.5,
                length: 15,
                // height: 2.5,
                height: 3,
                weight: 0.5,
            },
            types: [],
        },
        {
            name: 'A6 - Retrato (15x10,5 cm)',
            id: 508,
            size: {
                width: 11,
                // width: 10.5,
                length: 15,
                // height: 2.5,
                height: 3,
                weight: 0.5,
            },
            types: [],
        },
        {
            name: 'A7 - Paisagem (7,5x10,5 cm)',
            id: 509,
            size: {
                // width: 7.5,
                width: 8,
                length: 11,
                // length: 10.5,
                height: 3,
                // height: 2.5,
                weight: 0.5,
            },
            types: [],
        },
        {
            name: 'A7 - Retrato (10,5x7,5 cm)',
            id: 510,
            size: {
                // width: 7.5,
                width: 8,
                length: 11,
                // length: 10.5,
                height: 3,
                // height: 2.5,
                weight: 0.5,
            },
            types: [],
        },
        {
            name: 'Colegial - Paisagem (18x24 cm)',
            id: 511,
            size: {
                width: 18,
                length: 24,
                // height: 2.5,
                height: 3,
                weight: 0.5,
            },
            types: [],
        },
        {
            name: 'Colegial - Retrato (24x18 cm)',
            id: 512,
            size: {
                width: 24,
                length: 18,
                // height: 2.5,
                height: 3,
                weight: 0.5,
            },
            types: [],
        },
    ],
};

export default initialValues;
